function cfg = validateEVConfig(cfg)
%VALIDATEEVCONFIG Fail early when time bases or physical dimensions disagree.

assert(cfg.sim.integrationStep > 0, 'Integration step must be positive.');
assert(cfg.sim.endTime > 0 && cfg.sim.endTime <= cfg.drive.duration, ...
    'Simulation duration must lie inside the generated drive cycle.');
assert(abs(round(cfg.sim.logStep/cfg.sim.integrationStep) - ...
    cfg.sim.logStep/cfg.sim.integrationStep) < 1e-10, ...
    'Log step must be an integer multiple of the RK4 step.');
assert(abs(round(cfg.sim.bmsStep/cfg.sim.integrationStep) - ...
    cfg.sim.bmsStep/cfg.sim.integrationStep) < 1e-10, ...
    'BMS step must be an integer multiple of the RK4 step.');
assert(cfg.drive.sampleRate == 1/cfg.sim.logStep, ...
    'Drive-cycle and output sample rates must match.');
assert(cfg.battery.nSeries >= 2 && cfg.battery.nParallel >= 1, ...
    'Battery series/parallel counts are invalid.');
assert(all(size(cfg.battery.lut.Voc) == ...
    [numel(cfg.battery.temperatureGridC), numel(cfg.battery.socGrid)]), ...
    'Battery LUT dimensions do not match the temperature/SoC grids.');
assert(all(cfg.battery.lut.R0(:) > 0) && all(cfg.battery.lut.R1(:) > 0) ...
    && all(cfg.battery.lut.R2(:) > 0) && all(cfg.battery.lut.C1(:) > 0) ...
    && all(cfg.battery.lut.C2(:) > 0), ...
    'All Thevenin resistance and capacitance values must be positive.');
assert(cfg.motor.maximumSpeedRpm > cfg.motor.baseSpeedRpm, ...
    'Motor maximum speed must exceed base speed.');
end

